"""Validation report (Markdown) — every anomaly is listed; nothing is dropped silently."""
from __future__ import annotations

from collections import Counter, defaultdict

from .item_types import ITEM_TYPES
from .model import Catalog
from .names import NameRegistry

EXPLAIN = {
    "negative-leaf": "Story link has a negative `page/n` leaf (the guide's `printed+1` rule failed, typically in bound-volume "
                     "items). Stored with `ia_leaf = NULL`; the app must locate the story by page number/OCR.",
    "unrecognized-row": "Text inside an issue block that is neither an entry, a continuation nor auction/ABE data.",
    "duplicate-issue-heading": "Same year+month heading appears twice; both kept, second slug gets `-2`.",
    "heading-out-of-order": "Heading breaks the guide's chronological order — the printed date is probably wrong.",
    "shared-ia-item-cleared": "Two issues link to the same IA item; the later one lost its link (availability `none`).",
    "issue-item-switched-to-story-links": "Issue link and all its story links point to different IA items; the story "
                                          "links' item is used (leaves refer to it).",
    "issue-item-from-story-links": "Issue had no 'Read issue' link; IA item taken from its story links.",
    "stories-link-several-items": "Stories of one issue link to several IA items; issue link kept.",
    "entry-missing-fields": "Entry without the 'title · credits · type' structure.",
    "unknown-type-code": "Type code not in the FictionMags list.",
    "bad-type-code": "Last field is not a type code.",
    "unknown-page-token": "Page prefix that is neither a number nor bc/fc/ifc/ibc/?.",
    "sub-item-without-parent": "`_NN)` sub-item with no preceding top-level entry.",
    "read-link-without-uri": "'Read issue at …' text without a link annotation.",
    "conflicting-issue-link": "Heading and 'Read issue' links point to different IA items.",
}


def render(cat: Catalog, reg: NameRegistry, counts: dict[str, int], cover_count: int, source_sha: str) -> str:
    issues = cat.issues
    stories = [s for i in issues for s in i.stories]
    out: list[str] = []
    w = out.append
    w("# Catalog build report — Amazing Stories\n")
    w(f"Generated by `tools/build_catalog.py` from `{cat.source}` (sha256 `{source_sha[:16]}…`). "
      "Re-running produces the same `catalog.db`.\n")
    w("## Totals\n")
    w("| | count |\n|---|---|")
    w(f"| Issues | {counts['issues']} |")
    w(f"| Stories / items | {counts['stories']} |")
    w(f"| People | {counts['people']} |")
    w(f"| Covers written | {cover_count} |")
    av = Counter(i.availability for i in issues)
    w(f"| Availability ia / hathitrust / none | {av['ia']} / {av['hathitrust']} / {av['none']} |")
    w(f"| Stories with IA leaf | {sum(1 for s in stories if s.ia_leaf is not None)} |")
    w(f"| Parse problems (listed below) | {len(cat.problems)} |\n")

    w("## Issues by year\n")
    w("| Year | Issues | with IA | Stories |\n|---|---|---|---|")
    by_year: dict[int, list] = defaultdict(list)
    for i in issues:
        by_year[i.year].append(i)
    for y in sorted(by_year):
        its = by_year[y]
        w(f"| {y} | {len(its)} | {sum(1 for i in its if i.ia_identifier)} | {sum(len(i.stories) for i in its)} |")
    w("")

    def listing(title: str, items: list[str]) -> None:
        w(f"## {title} ({len(items)})\n")
        if not items:
            w("None.\n")
            return
        w(", ".join(items) + "\n")

    listing("Issues without IA link", [i.slug for i in issues if not i.ia_identifier])
    listing("Issues without cover", [i.slug for i in issues if not i.cover_image])
    listing("Issues without stories", [i.slug for i in issues if not i.stories])
    listing("Issues without cover artist (no 'cover by' in the guide, no `cv` item)",
            [i.slug for i in issues if not i.cover_artist_raw])
    listing("Issues without editor (no `ed` item in the guide's contents)",
            [i.slug for i in issues if not any(s.type_code == "ed" and s.credits for s in i.stories)])

    w("## Type codes\n")
    w("FictionMags Index item types (http://www.philsp.com/docs/fm_item_types.html). `_NN)` entries are items "
      "inside a group (e.g. chapters of a `gp`), `bc.` = back cover.\n")
    w("| Code | Meaning | Count |\n|---|---|---|")
    for code, n in Counter(s.type_code for s in stories).most_common():
        w(f"| `{code}` | {ITEM_TYPES.get(code or '', '**unknown**')} | {n} |")
    w("")
    rare = [c for c, n in Counter(s.type_code for s in stories).items() if n <= 3]
    listing("Unusual type codes (≤ 3 uses)", [f"`{c}`" for c in sorted(rare, key=str)])

    w("## Parse problems\n")
    kinds = Counter(p.kind for p in cat.problems)
    if not kinds:
        w("None.\n")
    for kind, n in kinds.most_common():
        w(f"### {kind} ({n})\n")
        w(EXPLAIN.get(kind, "") + "\n")
        w("| Guide page | Text | Detail |\n|---|---|---|")
        for p in (p for p in cat.problems if p.kind == kind):
            w(f"| {p.page} | {_md(p.text[:140])} | {_md(p.detail[:160])} |")
        w("")

    w("## Name normalization\n")
    merged = reg.merged_variants()
    w(f"Merged automatically (same name up to spacing/punctuation/case/accents, titles such as Capt./Dr. and "
      f"degrees such as Ph.D./M. D./U. S. A.; Jr./Sr. are never merged). Most frequent form is displayed: "
      f"{len(merged)}\n")
    for disp, forms in merged:
        w(f"- **{_md(disp)}** ← " + ", ".join(f"`{f}`" for f in forms))
    w("")
    dups = reg.possible_duplicates()
    w(f"Possible duplicates, **not** merged (same surname + first initial; many are pseudonyms or relatives — "
      f"review manually): {len(dups)}\n")
    for a, b in dups:
        w(f"- {_md(a)} / {_md(b)}")
    w("")
    return "\n".join(out)


def _md(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")
