"""Report for the Internet Archive collections (docs/catalog-sources.md): what was chosen per issue, which scans were
kept as alternates, and every skipped item with its reason — nothing is dropped silently."""
from __future__ import annotations

from collections import Counter

from .model import Catalog


def render(collections: list[tuple[dict, Catalog, dict[str, list[str]], list[tuple[str, str]]]]) -> str:
    out: list[str] = []
    w = out.append
    w("# Catalog sources report — Internet Archive collections\n")
    w("Generated by `tools/build_catalog.py` from the snapshots in `tools/sources/ia/` (adapter "
      "`tools/adapters/ia_collection.py`, rules in `tools/sources.toml`). One issue per date; the best scan is chosen by: "
      "page images + OCR available, then penalties (missing pages −30, foreign reprint −40, ads removed −15, "
      "image/PDF re-upload −5, modified −5), then the most pages.\n")
    w("| Magazine | Collection | Items | Issues | Years | Alternate scans | Skipped |\n|---|---|---|---|---|---|---|")
    for m, cat, alts, skipped in collections:
        items = len(cat.issues) + sum(len(v) for v in alts.values()) + len(skipped)
        years = f"{cat.issues[0].year}–{cat.issues[-1].year}" if cat.issues else "—"
        w(f"| {m['name']} | `{m['collection']}` | {items} | {len(cat.issues)} | {years} | "
          f"{sum(len(v) for v in alts.values())} | {len(skipped)} |")
    w("")
    for m, cat, alts, skipped in collections:
        w(f"## {m['name']}\n")
        flagged = Counter(p.detail for p in cat.problems)
        if flagged:
            w("Chosen scans that still carry a penalty (no better scan of that issue): " +
              ", ".join(f"{k} ×{v}" for k, v in flagged.most_common()) + ".\n")
        if skipped:
            w("### Skipped\n")
            w("| Item | Reason |\n|---|---|")
            for ident, why in skipped:
                w(f"| `{ident}` | {why} |")
            w("")
        w("<details><summary>Issues (chosen scan · alternates)</summary>\n")
        w("| Issue | Vol/No | Chosen scan | Alternates |\n|---|---|---|---|")
        for i in cat.issues:
            vn = f"{i.volume}/{i.number}" if i.volume is not None else ""
            alt = ", ".join(f"`{a}`" for a in alts.get(i.ia_identifier or "", []))
            w(f"| {i.title.split(', ', 1)[-1]} | {vn} | `{i.ia_identifier}` | {alt} |")
        w("\n</details>\n")
    return "\n".join(out).rstrip()
